apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./todo_app/manifests/todo-app-pvc.yaml
  - ./todo_app/manifests/deployment.yaml
  - ./todo_app/manifests/service.yaml
  - ./todo_app/manifests/ingress.yaml

  - ./todo_app_backend/manifests/secret.yaml
  - ./todo_app_backend/manifests/StatefulSet.yaml
  - ./todo_app_backend/manifests/deployment.yaml
  - ./todo_app_backend/manifests/service.yaml
  - ./todo_app_backend/manifests/ingress.yaml

  - ./todo_app_random/manifests/cornjob.yaml