apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: exercises
  name: ping-pong-ingress
spec:
  rules:
  - http:
      paths:
      - path: /pingpong
        pathType: Prefix
        backend:
          service:
            name: ping-pong-svc
            port:
              number: 18081
      - path: /pings
        pathType: Prefix
        backend:
          service:
            name: ping-pong-svc
            port:
              number: 18081