apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: todo-app-backend-svc
spec:
  type: ClusterIP
  selector:
    app: todo-app-backend
  ports:
    - port: 18083
      protocol: TCP
      targetPort: 8080