apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hourly-image-ingress
spec:
  rules:
  - http:
      paths:
      - path: /image
        pathType: Prefix
        backend:
          service:
            name: hourly-image-svc
            port:
              number: 18082