apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: todo-app-pv
          persistentVolumeClaim:
            claimName: todo-app-pvc
      containers:
        - name: todo-app
          image: todo-app:1.3
          volumeMounts:
            - name: todo-app-pv
              mountPath: /usr/src/app/todo-app-pv
          env:
            - name: IMAGE_PATH
              value: ./todo-app-pv/image.jpg
            - name: TODO_BACKEND_ADDRESS
              value: http://localhost
            - name: PORT
              value: "8080"
            - name: GIN_MODE
              value: release
