apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: project
  name: todo-app-ingress
spec:
  rules:
  - http:
      paths:
      - path: /image
        pathType: Prefix
        backend:
          service:
            name: todo-app-svc
            port:
              number: 18082
      - path: /todo-app
        pathType: Prefix
        backend:
          service:
            name: todo-app-svc
            port:
              number: 18082              